default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: salary_dev

test:
  <<: *default
  database: salary_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>