default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: salary_dev

test:
  <<: *default
  database: salary_test

pproduction:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>